# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0480b32e03a25775a8762a85474d5fbe08826a5559e864e9441b8bba512d6e8c8c6ff7e01d933de130e16080516d385b9968ae57be9a103a1cf6e04e7b0984d7

test:
  secret_key_base: 9fe052c1e420c7b917ea7631693e6da09778b90537bdb5167afde963bd1170ec6e933a78f1bda0ad766fe85312b42c7616e75d9fc7fe50aae1495092ee7b43dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
